#!/bin/bash

# Test script for iteration dropdown feature
# This script helps verify the iteration dropdown functionality

echo "🧪 Testing Iteration Dropdown Feature"
echo "======================================"
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${YELLOW}Prerequisites:${NC}"
echo "✓ Backend server must be running"
echo "✓ Flutter app must be running"
echo "✓ User must be logged in"
echo "✓ At least one checklist with iterations (reverted at least once)"
echo ""

echo -e "${GREEN}Test Checklist:${NC}"
echo ""

echo "□ TEST 1: Fresh Checklist (No Iterations)"
echo "  1. Open a checklist that has never been reverted"
echo "  2. Verify: No dropdown button appears next to questions"
echo "  3. Verify: Normal editing works"
echo ""

echo "□ TEST 2: Checklist with Iterations"
echo "  1. Open a checklist that has been reverted at least once"
echo "  2. Verify: Dropdown button with history icon appears next to each question"
echo "  3. Verify: Dropdown badge has green background"
echo "  4. Verify: Dropdown shows 'Current (vN)' as first option"
echo ""

echo "□ TEST 3: View Past Iteration"
echo "  1. Click dropdown on any question"
echo "  2. Select 'Iteration 1' or 'Iteration 2'"
echo "  3. Verify: Orange warning banner appears: 'Viewing Iteration N (Read-only)'"
echo "  4. Verify: Dropdown badge turns orange"
echo "  5. Verify: Question shows historical answer (Yes/No)"
echo "  6. Verify: Remark field shows historical remark"
echo "  7. Verify: Historical images are displayed"
echo "  8. Verify: Category/Severity show historical values (reviewer only)"
echo ""

echo "□ TEST 4: Read-Only Mode"
echo "  1. While viewing past iteration"
echo "  2. Try to click radio buttons"
echo "  3. Verify: Radio buttons are disabled"
echo "  4. Try to edit remark field"
echo "  5. Verify: Remark field is disabled"
echo "  6. Try to click image picker button"
echo "  7. Verify: Image picker is disabled"
echo "  8. Try to change category/severity (reviewer)"
echo "  9. Verify: Dropdowns are disabled"
echo ""

echo "□ TEST 5: Switch Back to Current"
echo "  1. Click dropdown and select 'Current (vN)'"
echo "  2. Verify: Orange warning banner disappears"
echo "  3. Verify: Dropdown badge turns green"
echo "  4. Verify: Current data is shown"
echo "  5. Verify: All form fields are editable again"
echo "  6. Try making a change"
echo "  7. Verify: Change is saved successfully"
echo ""

echo "□ TEST 6: Multiple Questions Independence"
echo "  1. Open checklist with multiple questions"
echo "  2. Set Question 1 to view Iteration 1"
echo "  3. Set Question 2 to view Iteration 2"  
echo "  4. Keep Question 3 on Current"
echo "  5. Verify: Each question shows its selected iteration independently"
echo "  6. Verify: State doesn't interfere between questions"
echo ""

echo "□ TEST 7: Role-Specific Data (Executor)"
echo "  1. Log in as executor"
echo "  2. View past iteration"
echo "  3. Verify: See executor's historical answer"
echo "  4. Verify: See executor's historical remark"
echo "  5. Verify: See executor's historical images"
echo ""

echo "□ TEST 8: Role-Specific Data (Reviewer)"
echo "  1. Log in as reviewer"
echo "  2. View same past iteration"
echo "  3. Verify: See reviewer's historical answer"
echo "  4. Verify: See reviewer's historical remark"
echo "  5. Verify: See reviewer's historical images"
echo "  6. Verify: See historical category"
echo "  7. Verify: See historical severity"
echo ""

echo "□ TEST 9: UI Responsiveness"
echo "  1. Rapidly switch between iterations"
echo "  2. Verify: UI updates smoothly without flickering"
echo "  3. Verify: No console errors"
echo "  4. Switch between questions while viewing iterations"
echo "  5. Verify: Each question maintains its selected iteration"
echo ""

echo "□ TEST 10: Edge Cases"
echo "  1. View iteration with empty remark"
echo "  2. Verify: Shows empty remark field correctly"
echo "  3. View iteration with no images"
echo "  4. Verify: No images displayed, no error"
echo "  5. View iteration with null category/severity"
echo "  6. Verify: Shows 'None' in dropdowns"
echo ""

echo ""
echo -e "${YELLOW}Known Limitations:${NC}"
echo "• Iterations are loaded per-question (will be optimized to load once per checklist)"
echo "• No comparison view between iterations (future enhancement)"
echo "• No visual diff highlighting (future enhancement)"
echo ""

echo -e "${GREEN}Common Issues & Solutions:${NC}"
echo ""
echo "Issue: Dropdown doesn't appear"
echo "Solution: Checklist must have at least 1 iteration (be reverted once)"
echo ""
echo "Issue: 'Not authenticated' error in console"
echo "Solution: Make sure user is logged in"
echo ""
echo "Issue: Wrong data in iteration"
echo "Solution: Check that questionId is passed correctly to SubQuestionCard"
echo ""

echo "======================================"
echo "📝 Record test results and report any issues"
echo ""
